title: MikeGuides Blog
description: "Guides, frameworks, and playbooks for smarter pricing, marketing, and automation."
# If you're serving at the project URL, set url to the GH Pages URL:
url: "https://mikeguides-creator.github.io"
baseurl: "/mikeguides-blog-v2"

markdown: kramdown

# You have custom layouts, so 'theme' is optional. You can keep it or remove it.
# theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  slugs:
    output: true
    permalink: /slugs/:name/
